[package]
name = "rust_demo"
version = "0.1.0"
authors = ["17692194556 <1643935980@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
